### ISSUE TITLE
Example of ouput

### ISSUE THREAD

**Issue by hongsw** [hongsw/ChatGPT-table2md-chrome-extension#24]
|                       | Cat                                                                                        | Turtle                                                                                                      | Human                                                                                                    |
|------------------------|--------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|
| Average lifespan       | 10-15 years                                                                                | 20-150+ years (depending on species)                                                                        | 72.6 years                                                                                               |
| Reproduction           | Prolific breeders, able to reproduce multiple times per year                               | Slow reproductive rate, some species lay eggs while others give birth to live young                         | Moderate reproductive rate, usually giving birth to one or a few offspring at a time                     |
| Social behavior        | Independent and solitary hunters, with some social interactions with other cats            | Solitary animals, some species form pair bonds or groupings during mating or nesting season                 | Highly social animals, forming complex social networks and relationships                                 |
| Environmental factors  | Affected by habitat loss, hunting, and other human activities                              | Vulnerable to pollution, habitat destruction, and climate change                                            | Affected by pollution, habitat destruction, and climate change, as well as cultural and societal factors |
| Behavioral adaptations | Agile and quick reflexes, nocturnal hunting behavior, and territoriality                   | Unique shell structure, various adaptations for feeding and swimming, and varying levels of social behavior | Complex cognitive and social adaptations, including language, tool use, and culture                      |
| Threats to lifespan    | Accidents, disease, predation, and human activities such as hunting and pet overpopulation | Habitat loss, pollution, disease, predation, and hunting                                                    | Accidents, disease, lifestyle-related illnesses, and societal issues such as war and poverty             |

**Comment by hongsw** [comment]
```
<table><thead><tr><th></th><th>Cat</th><th>Turtle</th><th>Human</th></tr></thead><tbody><tr><td>Average lifespan</td><td>10-15 years</td><td>20-150+ years (depending on species)</td><td>72.6 years</td></tr><tr><td>Reproduction</td><td>Prolific breeders, able to reproduce multiple times per year</td><td>Slow reproductive rate, some species lay eggs while others give birth to live young</td><td>Moderate reproductive rate, usually giving birth to one or a few offspring at a time</td></tr><tr><td>Social behavior</td><td>Independent and solitary hunters, with some social interactions with other cats</td><td>Solitary animals, some species form pair bonds or groupings during mating or nesting season</td><td>Highly social animals, forming complex social networks and relationships</td></tr><tr><td>Environmental factors</td><td>Affected by habitat loss, hunting, and other human activities</td><td>Vulnerable to pollution, habitat destruction, and climate change</td><td>Affected by pollution, habitat destruction, and climate change, as well as cultural and societal factors</td></tr><tr><td>Behavioral adaptations</td><td>Agile and quick reflexes, nocturnal hunting behavior, and territoriality</td><td>Unique shell structure, various adaptations for feeding and swimming, and varying levels of social behavior</td><td>Complex cognitive and social adaptations, including language, tool use, and culture</td></tr><tr><td>Threats to lifespan</td><td>Accidents, disease, predation, and human activities such as hunting and pet overpopulation</td><td>Habitat loss, pollution, disease, predation, and hunting</td><td>Accidents, disease, lifestyle-related illnesses, and societal issues such as war and poverty</td></tr></tbody></table>
```

**Comment by hongsw** [comment]
![image](https://user-images.githubusercontent.com/1100974/224520350-b7686da3-baa6-4f2f-bdaf-e2ee2a3eb829.png)
@baechanghyeon 위의 예시가 잘 변환되나요 첫번째 로우의 컬럼이 빈공간이라서 https://tableconvert.com/html-to-markdown 는 잘안되더라구요 한컬럼이 없이 시작해요

**Comment by hongsw** [comment]
https://sites.google.com/view/chatgptablemate/%ED%99%88 예시 만들고 있는중

**Comment by baechanghyeon** [comment]
![bodyObserve](https://user-images.githubusercontent.com/28972561/224523822-7214ec8f-a962-4fb5-9020-f392b72258df.gif)

Observe targetNode를 body로 바꾸니까 정상적으로 작동합니다 !
그리고 PNG 기능도 말씀하신 canvas로 시도하고 있는데 정상적으로 작동하면 같이 묶어서(+ 오류해결) PR 올리겠습니다.

**Comment by hongsw** [comment]
첫번째 커럼이 비어있어도 잘 테이블 변환이 되나요? 위의 예시는 그런 말입니다만 @baechanghyeon

**Comment by jaeyeong815** [comment]
@hongsw 제가 변환 기능을 구현하면서 컬럼 비어있는 해당 경우를 테스트 해봤는데, 잘 변환 되는거 확인했었습니다. 현재 테스트 할 때 안된다고 말씀주신건가요?
