### ISSUE TITLE
popup page

### ISSUE THREAD

**Issue by jaeyeong815** [hongsw/ChatGPT-table2md-chrome-extension#34]
현재 팝업 페이지

<img width="310" alt="image" src="https://user-images.githubusercontent.com/85178602/224860327-88fd674b-5e97-469b-ac8c-cdedfbccb17f.png">

팝업에 들어갈 내용 (계속 추가)
- github 링크

**Comment by jaeyeong815** [comment]
대체적으로 심플하게 구성되어있음
상단에 이름 크게 / 이름 아래 작게 설명
백준허브 팝업처럼 아이콘으로
깃헙 / 메일 / 등등..

chatgpt-screenshot-ex 팝업
<img width="437" alt="image" src="https://user-images.githubusercontent.com/85178602/224872826-0b4f1ecf-c25e-40f6-bbfc-264f52b998fa.png">

chatGPT to Notion 팝업
<img width="262" alt="image" src="https://user-images.githubusercontent.com/85178602/224872921-49922190-9b4e-404d-9703-a324548251e0.png">

chatGPT for Google 팝업 (톱니바퀴 누르면 설정페이지로 이동)
<img width="408" alt="image" src="https://user-images.githubusercontent.com/85178602/224873343-36875038-b35a-4946-91de-362f5f806080.png">

Copy as Markdown 팝업 없음 (클릭하면 github 페이지로 이동)

백준허브 팝업 (이름/설명/하단에 연락할 수 있는 수단 안내)
<img width="355" alt="image" src="https://user-images.githubusercontent.com/85178602/224874100-de888b29-6de9-4f16-9fa0-aecc3f7e9677.png">

**Comment by jaeyeong815** [comment]
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/85178602/224905289-67862a35-e8ca-4a1d-82b0-84796691779a.gif)

추가 스타일링 하기 전 작업물

**Comment by jaeyeong815** [comment]
[버튼 스타일 참고한 링크](https://codepen.io/ShadowShahriar/pen/XWaLPOv)

**Comment by hongsw** [comment]
디자인 분석도 많이 했군요 ㅎ
